name: Pylint

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: 3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pylint
        python -m pip install -r requirements.txt
    - name: Analysing the code with pylint 
      working-directory: src
      run: |
        pylint --fail-under=5.0 $(git ls-files './*.py')
